### ISSUE TITLE
No 'SNFG CARB SYMBOL' type for UAP in 2HYV-carb.cif

### ISSUE THREAD

**Issue by arose** [pdbxmmcifwg/carbohydrate-extension#1]
Hi, there is no 'SNFG CARB SYMBOL' _pdbx_chem_comp_identifier.type in examples/models/2HYV-carb.cif. Is that intentional or is it missing?

On a related note, there is also no 'COMMON NAME' type in that file but in the other examples there is.

**Comment by shaochenghua** [comment]
Intentional, currently only exact match has SNFG symbol. In 2HYV, all monosaccharides are modified beyond the current list of SNFG, UAP has ring modification, SGN and IDS are sulfo-modified.

**Comment by shaochenghua** [comment]
So is common name, there is no common name for these modified sugar

**Comment by arose** [comment]
I see, thanks @shaochenghua. So I would draw it as a white flat hexagon as per https://www.ncbi.nlm.nih.gov/glycans/snfg.html or do you have another suggestion?

**Comment by arose** [comment]
> So I would draw it as a white flat hexagon as per https://www.ncbi.nlm.nih.gov/glycans/snfg.html or do you have another suggestion?

Agreement for sugars without a SNFG symbol is to draw them as a flat polygon with as many corners as there are atoms in the sugar ring.

**Comment by shaochenghua** [comment]
Good. Thx
