### ISSUE TITLE
Distinction between oligosaccharide and polysaccharide

### ISSUE THREAD

**Issue by yokochi47** [pdbxmmcifwg/carbohydrate-extension#3]
Hi,

PDBj has received a comment on wwPDB carbohydrate remediation proposal from a carbohydrate expert in Japan.

Oligosaccharides differ polysaccharides in many aspects, such as glycosidic linkage (alpha or beta), metabolism, biosynthesis, and their function (protein modification or storing energy) so that glycan researchers focus on one or the other. Therefore, the distinction between oligosaccharides and polysaccharides is strictly applied in the glycan research field. Term “glycan” or “carbohydrate” in general are a broader concept that includes oligosaccharides and polysaccharide.
Please refer to ontology established by international community of glycan research: https://bioportal.bioontology.org/ontologies/GLYCO

As shown in the Glycomics Ontology, the polysaccharide is classified into separate category from the oligosaccharide. But, the first figure in the proposal may be misleading. The footer “Polysaccharides”, next to "Proteins/Nucleotide", is to be replaced with “Carbohydrates” solely or "Oligosaccharides/Polysaccharides”.

To clear the distinction further, entity.type data item in current dictionary for carbohydrate remediation can have polysaccharide as well as oligosaccharide, which is the only defined enumeration at present. The extension of entity.type can provide more useful information for the glycan researchers if we add “N-glycan oligosaccharide” and “O-glycan oligosaccharide” for glycoprotein case.
<pre>
loop_
_item_enumeration.value
_item_enumeration.details
  oligosaccharide .
  polysaccharide .
# candidates for additional enumerations
  “N-glycan oligosaccharide” .
  “O-glycan oligosaccharide” .
</pre>
I am also confusing whether all non-branched carbohydrates such as disaccharides, or polysaccharide, incorporated into the carbohydrate remediation or not.

Thank you,

**Comment by shaochenghua** [comment]
I believe Jasmine has replied in email about the issues, so I'm closing this. If this is not the case, please let me know. Thx.
